apiVersion: v1
kind: Service
metadata:
  name: grpc-payment-service
spec:
  type: LoadBalancer
  selector:
    app: grpc-payment-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50051