apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-payment-service
  template:
    metadata:
      labels:
        app: rest-payment-service
    spec:
      containers:
      - name: rest-payment-service
        image: gcr.io/{PROJECT_ID}/rest-payment-service:v1
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"