apiVersion: v1
kind: Service
metadata:
  name: rest-payment-service
spec:
  type: LoadBalancer
  selector:
    app: rest-payment-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081